// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/RSSp.h"
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// evd_dnorm
double evd_dnorm(const MapA par, const MapA D, const MapA quh);
RcppExport SEXP _RSSp_evd_dnorm(SEXP parSEXP, SEXP DSEXP, SEXP quhSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const MapA >::type par(parSEXP);
    Rcpp::traits::input_parameter< const MapA >::type D(DSEXP);
    Rcpp::traits::input_parameter< const MapA >::type quh(quhSEXP);
    rcpp_result_gen = Rcpp::wrap(evd_dnorm(par, D, quh));
    return rcpp_result_gen;
END_RCPP
}
// evd_dnorm_grad_stan
Eigen::ArrayXd evd_dnorm_grad_stan(const MapA par, const MapA D, const MapA quh);
RcppExport SEXP _RSSp_evd_dnorm_grad_stan(SEXP parSEXP, SEXP DSEXP, SEXP quhSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const MapA >::type par(parSEXP);
    Rcpp::traits::input_parameter< const MapA >::type D(DSEXP);
    Rcpp::traits::input_parameter< const MapA >::type quh(quhSEXP);
    rcpp_result_gen = Rcpp::wrap(evd_dnorm_grad_stan(par, D, quh));
    return rcpp_result_gen;
END_RCPP
}
// evd_dnorm_stan
double evd_dnorm_stan(const MapA par, const MapA D, const MapA quh);
RcppExport SEXP _RSSp_evd_dnorm_stan(SEXP parSEXP, SEXP DSEXP, SEXP quhSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const MapA >::type par(parSEXP);
    Rcpp::traits::input_parameter< const MapA >::type D(DSEXP);
    Rcpp::traits::input_parameter< const MapA >::type quh(quhSEXP);
    rcpp_result_gen = Rcpp::wrap(evd_dnorm_stan(par, D, quh));
    return rcpp_result_gen;
END_RCPP
}
// evd_dnorm_hess_stan
Eigen::MatrixXd evd_dnorm_hess_stan(const MapA par, const MapA D, const MapA quh);
RcppExport SEXP _RSSp_evd_dnorm_hess_stan(SEXP parSEXP, SEXP DSEXP, SEXP quhSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const MapA >::type par(parSEXP);
    Rcpp::traits::input_parameter< const MapA >::type D(DSEXP);
    Rcpp::traits::input_parameter< const MapA >::type quh(quhSEXP);
    rcpp_result_gen = Rcpp::wrap(evd_dnorm_hess_stan(par, D, quh));
    return rcpp_result_gen;
END_RCPP
}
// estimate_pve
double estimate_pve(const MapA cvec, const MapA D, const MapA quh, int sample_size);
RcppExport SEXP _RSSp_estimate_pve(SEXP cvecSEXP, SEXP DSEXP, SEXP quhSEXP, SEXP sample_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const MapA >::type cvec(cvecSEXP);
    Rcpp::traits::input_parameter< const MapA >::type D(DSEXP);
    Rcpp::traits::input_parameter< const MapA >::type quh(quhSEXP);
    Rcpp::traits::input_parameter< int >::type sample_size(sample_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(estimate_pve(cvec, D, quh, sample_size));
    return rcpp_result_gen;
END_RCPP
}
// simuh_dir_cpp
Eigen::MatrixXd simuh_dir_cpp(double sigu, double bias, int nreps, Eigen::MatrixXd& Q, Eigen::ArrayXd& D, Rcpp::StringVector fgeneids, Eigen::MatrixXd usim);
RcppExport SEXP _RSSp_simuh_dir_cpp(SEXP siguSEXP, SEXP biasSEXP, SEXP nrepsSEXP, SEXP QSEXP, SEXP DSEXP, SEXP fgeneidsSEXP, SEXP usimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type sigu(siguSEXP);
    Rcpp::traits::input_parameter< double >::type bias(biasSEXP);
    Rcpp::traits::input_parameter< int >::type nreps(nrepsSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< Eigen::ArrayXd& >::type D(DSEXP);
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type fgeneids(fgeneidsSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type usim(usimSEXP);
    rcpp_result_gen = Rcpp::wrap(simuh_dir_cpp(sigu, bias, nreps, Q, D, fgeneids, usim));
    return rcpp_result_gen;
END_RCPP
}
// block_mat_mul
Rcpp::NumericMatrix block_mat_mul(Rcpp::ListOf<Rcpp::NumericMatrix>& mat_l, Rcpp::NumericMatrix& ymat, bool transpose_mat_l);
RcppExport SEXP _RSSp_block_mat_mul(SEXP mat_lSEXP, SEXP ymatSEXP, SEXP transpose_mat_lSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::ListOf<Rcpp::NumericMatrix>& >::type mat_l(mat_lSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix& >::type ymat(ymatSEXP);
    Rcpp::traits::input_parameter< bool >::type transpose_mat_l(transpose_mat_lSEXP);
    rcpp_result_gen = Rcpp::wrap(block_mat_mul(mat_l, ymat, transpose_mat_l));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RSSp_evd_dnorm", (DL_FUNC) &_RSSp_evd_dnorm, 3},
    {"_RSSp_evd_dnorm_grad_stan", (DL_FUNC) &_RSSp_evd_dnorm_grad_stan, 3},
    {"_RSSp_evd_dnorm_stan", (DL_FUNC) &_RSSp_evd_dnorm_stan, 3},
    {"_RSSp_evd_dnorm_hess_stan", (DL_FUNC) &_RSSp_evd_dnorm_hess_stan, 3},
    {"_RSSp_estimate_pve", (DL_FUNC) &_RSSp_estimate_pve, 4},
    {"_RSSp_simuh_dir_cpp", (DL_FUNC) &_RSSp_simuh_dir_cpp, 7},
    {"_RSSp_block_mat_mul", (DL_FUNC) &_RSSp_block_mat_mul, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_RSSp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
