# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' evd_dnorm
#' 
#' This function computes the RSSp negative log likelihood
#' @param par a length 2 numeric vector.  par[1] corresponds to the sigma_u parameter, and par[2] corresponds to the confounding parameter
#' @param dvec. The eigenvalues of the LD matrix
#' @param quh The precomputed matrix vector product Q%*%u_hat (passed as a vector)
evd_dnorm <- function(par, dvec, quh) {
    .Call('_RSSp_evd_dnorm', PACKAGE = 'RSSp', par, dvec, quh)
}

#' evd_dnorm
#' 
#' This function computes the RSSp negative log likelihood gradient
#' @param par a length 2 numeric vector.  par[1] corresponds to the sigma_u parameter, and par[2] corresponds to the confounding parameter
#' @param dvec. The eigenvalues of the LD matrix
#' @param quh The precomputed matrix vector product Q%*%u_hat (passed as a vector)
evd_dnorm_grad <- function(par, dvec, quh) {
    .Call('_RSSp_evd_dnorm_grad', PACKAGE = 'RSSp', par, dvec, quh)
}

#' evd_dnorm_grad_stan
#' 
#' This is an attempt to use stan's AD features to calculate a gradient 
#' for the RSSp likelihood
#' 
#' //' @param par a length 2 numeric vector.  par[1] corresponds to the sigma_u parameter, and par[2] corresponds to the confounding parameter
#' @param dvec. The eigenvalues of the LD matrix
#' @param quh The precomputed matrix vector product Q%*%u_hat (passed as a vector)
evd_dnorm_grad_stan <- function(par, dvec, quh) {
    .Call('_RSSp_evd_dnorm_grad_stan', PACKAGE = 'RSSp', par, dvec, quh)
}

rcppeigen_hello_world <- function() {
    .Call('_RSSp_rcppeigen_hello_world', PACKAGE = 'RSSp')
}

rcppeigen_outerproduct <- function(x) {
    .Call('_RSSp_rcppeigen_outerproduct', PACKAGE = 'RSSp', x)
}

rcppeigen_innerproduct <- function(x) {
    .Call('_RSSp_rcppeigen_innerproduct', PACKAGE = 'RSSp', x)
}

rcppeigen_bothproducts <- function(x) {
    .Call('_RSSp_rcppeigen_bothproducts', PACKAGE = 'RSSp', x)
}

