# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' variance  
#' @template RSSp_stat
NULL

#' RSSp marginalized likelihood function
#' 
#' Compute the negative of the marginalized RSSp log-likelihood
#' @template RSSp_stat
evd_dnorm <- function(par, dvec, quh) {
    .Call('_RSSp_evd_dnorm', PACKAGE = 'RSSp', par, dvec, quh)
}

#' Compute the posterior mean of `crossprod(Q,u)` given eigenvalues, `crossprod(Q,u_hat)`,sigma_u^2 and confounding levels.
#' @template RSSp_stat
evd_post_mean <- function(par, dvec, quh) {
    .Call('_RSSp_evd_post_mean', PACKAGE = 'RSSp', par, dvec, quh)
}

#' Compute the posterior variance of `crossprod(Q,u)` given eigenvalues, `crossprod(Q,u_hat)`,sigma_u^2 and confounding levels.
#' @template RSSp_stat
evd_post_var <- function(par, dvec) {
    .Call('_RSSp_evd_post_var', PACKAGE = 'RSSp', par, dvec)
}

#' evd_dnorm_grad
#' 
#' This function computes the RSSp negative log likelihood gradient
#' @template RSSp_stat
evd_dnorm_grad <- function(par, dvec, quh) {
    .Call('_RSSp_evd_dnorm_grad', PACKAGE = 'RSSp', par, dvec, quh)
}

#' evd_dnorm_grad_stan
#' 
#' This is an attempt to use stan's AD features to calculate a gradient 
#' for the RSSp likelihood
#' 
#' @template RSSp_stat
evd_dnorm_grad_stan <- function(par, dvec, quh) {
    .Call('_RSSp_evd_dnorm_grad_stan', PACKAGE = 'RSSp', par, dvec, quh)
}

#' evd_dnorm_hess_stan
#' 
#' This is an attempt to use stan's AD features to calculate a hessian 
#' for the RSSp likelihood
#' 
#' @template RSSp_stat
evd_dnorm_hess_stan <- function(par, dvec, quh) {
    .Call('_RSSp_evd_dnorm_hess_stan', PACKAGE = 'RSSp', par, dvec, quh)
}

posterior_mean_D <- function(sigu, confound, dvec) {
    .Call('_RSSp_posterior_mean_D', PACKAGE = 'RSSp', sigu, confound, dvec)
}

posterior_mean_U <- function(sigu, confound, dvec, quh, Q) {
    .Call('_RSSp_posterior_mean_U', PACKAGE = 'RSSp', sigu, confound, dvec, quh, Q)
}

posterior_mean_Beta <- function(sigu, confound, dvec, quh, Q, se) {
    .Call('_RSSp_posterior_mean_Beta', PACKAGE = 'RSSp', sigu, confound, dvec, quh, Q, se)
}

posterior_mean_Y <- function(sigu, confound, dvec, quh, Q, se, x) {
    .Call('_RSSp_posterior_mean_Y', PACKAGE = 'RSSp', sigu, confound, dvec, quh, Q, se, x)
}

posterior_var_Beta <- function(sigu, confound, dvec, quh, Q, se) {
    .Call('_RSSp_posterior_var_Beta', PACKAGE = 'RSSp', sigu, confound, dvec, quh, Q, se)
}

simuh_dir_cpp <- function(sigu, bias, nreps, Q, D, fgeneids, usim) {
    .Call('_RSSp_simuh_dir_cpp', PACKAGE = 'RSSp', sigu, bias, nreps, Q, D, fgeneids, usim)
}

block_mat_mul <- function(mat_l, ymat, transpose_mat_l = FALSE) {
    .Call('_RSSp_block_mat_mul', PACKAGE = 'RSSp', mat_l, ymat, transpose_mat_l)
}

